spring.application.name=mascotaorden

spring.datasource.url=jdbc:oracle:thin:@ugnfm3wc8em1nfqi_high
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${WALLET_PATH:${user.dir}/Wallet_UGNFM3WC8EM1NFQI}
spring.datasource.username=${DB_USERNAME:CHAVEZ}
spring.datasource.password=ClaseFS123456-
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

logging.level.root=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG
